name: workshop25
channels:
    - conda-forge
    - bioconda
    - nodefaults
dependencies:
    - python>=3.11
    - pip>=21.1
    - scanpy
    - pip:
        - jupyterlab
        - ipywidgets
        - pandas>2
        - scanpy>=1.8.1
        - leidenalg>=0.8.1
        - numpy>=1.18.1
        - scipy>=1.5.0
        - scikit-misc>=0.1.3
        - scikit-learn>=0.23.1
        - ipykernel
        - matplotlib>3.8.4
        - decoupler==2.1.1
        - fastcluster
